// Code generated by protoc-gen-go. DO NOT EDIT.
// source: numbers.proto

package numbers

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Number struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Number) Reset()         { *m = Number{} }
func (m *Number) String() string { return proto.CompactTextString(m) }
func (*Number) ProtoMessage()    {}
func (*Number) Descriptor() ([]byte, []int) {
	return fileDescriptor_874cc518860a4f8b, []int{0}
}

func (m *Number) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Number.Unmarshal(m, b)
}
func (m *Number) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Number.Marshal(b, m, deterministic)
}
func (m *Number) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Number.Merge(m, src)
}
func (m *Number) XXX_Size() int {
	return xxx_messageInfo_Number.Size(m)
}
func (m *Number) XXX_DiscardUnknown() {
	xxx_messageInfo_Number.DiscardUnknown(m)
}

var xxx_messageInfo_Number proto.InternalMessageInfo

func (m *Number) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type BeginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginRequest) Reset()         { *m = BeginRequest{} }
func (m *BeginRequest) String() string { return proto.CompactTextString(m) }
func (*BeginRequest) ProtoMessage()    {}
func (*BeginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_874cc518860a4f8b, []int{1}
}

func (m *BeginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginRequest.Unmarshal(m, b)
}
func (m *BeginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginRequest.Marshal(b, m, deterministic)
}
func (m *BeginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginRequest.Merge(m, src)
}
func (m *BeginRequest) XXX_Size() int {
	return xxx_messageInfo_BeginRequest.Size(m)
}
func (m *BeginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Number)(nil), "numbers.Number")
	proto.RegisterType((*BeginRequest)(nil), "numbers.BeginRequest")
}

func init() { proto.RegisterFile("numbers.proto", fileDescriptor_874cc518860a4f8b) }

var fileDescriptor_874cc518860a4f8b = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x2b, 0xcd, 0x4d,
	0x4a, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xe4, 0xb8,
	0xd8, 0xfc, 0xc0, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xd6, 0x20, 0x08, 0x47, 0x89, 0x8f, 0x8b, 0xc7, 0x29, 0x35, 0x3d, 0x33, 0x2f, 0x28,
	0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0xc4, 0xc8, 0x81, 0x8b, 0xd3, 0x3d, 0x35, 0x2f, 0xb5, 0x28, 0xb1,
	0x24, 0xbf, 0x48, 0xc8, 0x98, 0x8b, 0x15, 0x2c, 0x29, 0x24, 0xaa, 0x07, 0x33, 0x1e, 0x59, 0xb1,
	0x14, 0x3f, 0x5c, 0x18, 0x62, 0x87, 0x12, 0x83, 0x01, 0x63, 0x12, 0x1b, 0xd8, 0x05, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x3c, 0x3c, 0xea, 0x92, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GeneratorClient is the client API for Generator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeneratorClient interface {
	Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (Generator_BeginClient, error)
}

type generatorClient struct {
	cc *grpc.ClientConn
}

func NewGeneratorClient(cc *grpc.ClientConn) GeneratorClient {
	return &generatorClient{cc}
}

func (c *generatorClient) Begin(ctx context.Context, in *BeginRequest, opts ...grpc.CallOption) (Generator_BeginClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Generator_serviceDesc.Streams[0], "/numbers.Generator/Begin", opts...)
	if err != nil {
		return nil, err
	}
	x := &generatorBeginClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Generator_BeginClient interface {
	Recv() (*Number, error)
	grpc.ClientStream
}

type generatorBeginClient struct {
	grpc.ClientStream
}

func (x *generatorBeginClient) Recv() (*Number, error) {
	m := new(Number)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GeneratorServer is the server API for Generator service.
type GeneratorServer interface {
	Begin(*BeginRequest, Generator_BeginServer) error
}

func RegisterGeneratorServer(s *grpc.Server, srv GeneratorServer) {
	s.RegisterService(&_Generator_serviceDesc, srv)
}

func _Generator_Begin_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BeginRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeneratorServer).Begin(m, &generatorBeginServer{stream})
}

type Generator_BeginServer interface {
	Send(*Number) error
	grpc.ServerStream
}

type generatorBeginServer struct {
	grpc.ServerStream
}

func (x *generatorBeginServer) Send(m *Number) error {
	return x.ServerStream.SendMsg(m)
}

var _Generator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "numbers.Generator",
	HandlerType: (*GeneratorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Begin",
			Handler:       _Generator_Begin_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "numbers.proto",
}
